[package]
name = "css-transform"
version = "1.0.0"
edition = "2018"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
polyhorn = { version = "0.3.1" }

[build-dependencies]
polyhorn-build = "0.3.1"
