[package]
name = "css-transform"
version = "1.0.0"
edition = "2018"
publish = false

[dependencies]
tokio = { version = "0.2.5", features = ["time"] }
polyhorn = "0.4.1"
yoyo = "0.4.1"

[build-dependencies]
polyhorn-build = "0.4.0"
